<?php
/**
 * @category   Webcreta
 * @package    Webcreta_Video
 * @author     sp.webcreta@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Webcreta\Video\Block;

/**
 * Video content block
 */
class Video extends \Magento\Framework\View\Element\Template
{
    public function __construct(
        \Magento\Framework\View\Element\Template\Context $context,
        \Magento\Catalog\Api\ProductRepositoryInterface $productRepository
    ) {
        $this->productRepository = $productRepository;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('Webcreta Video Module'));
        
        return parent::_prepareLayout();
    }
    public function getProductUrlKey($productId)
    {
        $_product = $this->productRepository->getById($productId);
        $urlkey = $_product->getProductUrl();
        return $urlkey;
    }
    public function getIsSubscribe($productId)
    {
        $_product = $this->productRepository->getById($productId);
        $isVideo = $_product->getIsVideo();
        return $isVideo;
    }
}
