<?php
/**
 * @category   Webcreta
 * @package    Webcreta_Video
 * @author     sp.webcreta@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Webcreta\Video\Block;

use Magento\Framework\View\Element\Template\Context;
use Webcreta\Video\Model\VideoFactory;
use Magento\Cms\Model\Template\FilterProvider;
/**
 * Video View block
 */
class VideoView extends \Magento\Framework\View\Element\Template
{
    /**
     * @var Video
     */
    protected $_video;
    public function __construct(
        Context $context,
        VideoFactory $video,
        FilterProvider $filterProvider
    ) {
        $this->_video = $video;
        $this->_filterProvider = $filterProvider;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('Webcreta Video Module View Page'));
        
        return parent::_prepareLayout();
    }

    public function getSingleData()
    {
        $id = $this->getRequest()->getParam('id');
        $video = $this->_video->create();
        $singleData = $video->load($id);
        if($singleData->getVideoId() || $singleData['video_id'] && $singleData->getStatus() == 1){
            return $singleData;
        }else{
            return false;
        }
    }
}