<?php
/**
 * @category   Webcreta
 * @package    Webcreta_Video
 * @author     sp.webcreta@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Webcreta\Video\Block;

use Magento\Framework\View\Element\Template\Context;
use Webcreta\Video\Model\VideoFactory;
/**
 * Video List block
 */
class VideoListData extends \Magento\Framework\View\Element\Template
{
    /**
     * @var Video
     */
    protected $_video;
    public function __construct(
        Context $context,
        VideoFactory $video,
        \Magento\Catalog\Api\ProductRepositoryInterface $productRepository
    ) {
        $this->_video = $video;
        $this->productRepository = $productRepository;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('Webcreta Video Module List Page'));
        
        if ($this->getVideoCollection()) {
            $pager = $this->getLayout()->createBlock(
                'Magento\Theme\Block\Html\Pager',
                'webcreta.video.pager'
            )->setAvailableLimit(array(5=>5,10=>10,15=>15))->setShowPerPage(true)->setCollection(
                $this->getVideoCollection()
            );
            $this->setChild('pager', $pager);
            $this->getVideoCollection()->load();
        }
        return parent::_prepareLayout();
    }

    public function getVideoCollection()
    {
        $page = ($this->getRequest()->getParam('p'))? $this->getRequest()->getParam('p') : 1;
        $pageSize = ($this->getRequest()->getParam('limit'))? $this->getRequest()->getParam('limit') : 5;

        $video = $this->_video->create();
        $collection = $video->getCollection();
        $collection->addFieldToFilter('status','1');
        //$video->setOrder('video_id','ASC');
        $collection->setPageSize($pageSize);
        $collection->setCurPage($page);

        return $collection;
    }
    public function getProductUrlKey($productId)
    {
        $_product = $this->productRepository->getById($productId);
        $urlkey = $_product->getProductUrl();
        return $urlkey;
    }
    public function getIsSubscribe($productId)
    {
        $_product = $this->productRepository->getById($productId);
        $isVideo = $_product->getIsVideo();
        return $isVideo;
    }
    public function getPagerHtml()
    {
        return $this->getChildHtml('pager');
    }
}