<?php
/**
 * @category   Webcreta
 * @package    Webcreta_Video
 * @author     sp.webcreta@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Webcreta\Video\Model\ResourceModel;

class Video extends \Magento\Framework\Model\ResourceModel\Db\AbstractDb
{
    /**
     * Define main table
     */
    protected function _construct()
    {
        $this->_init('webcreta_video', 'video_id');   //here "webcreta_video" is table name and "video_id" is the primary key of custom table
    }
}