<?php
/**
 * @category   Webcreta
 * @package    Webcreta_Video
 * @author     sp.webcreta@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Webcreta\Video\Model\ResourceModel\Video;
 
class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{
    protected $_idFieldName = 'video_id';
    /**
     * Define model & resource model
     */
    protected function _construct()
    {
        $this->_init(
            'Webcreta\Video\Model\Video',
            'Webcreta\Video\Model\ResourceModel\Video'
        );
    }
}